name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11.0.7
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle lint
      run: ./gradlew lintDebug lintFixDebug 
    - name: Gradle build
      run: ./gradlew build
    - name: Gradle unit test
      run: ./gradlew build check testDebugUnitTest
  
  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          - 23
          - 29
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      ## Actual task
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck --no-daemon --stacktrace

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: insrumentation-test-results
          path: ./**/build/reports/androidTests/connected/**

