name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle lint
      run: ./gradlew lintDebug lintFixDebug 
    - name: Gradle build
      run: ./gradlew build
    - name: Gradle unit test
      run: ./gradlew build check testDebugUnitTest

